name: "Create Tag"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string 
      runs-on:
        type: string
        default: ubuntu-latest

jobs:
  tag:
    name: "Create Tag ${{inputs.version}}"
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push Tag
        id: push-tag
        run: |
          echo "tag: ${{inputs.version}}"
          git tag ${{inputs.version}}
          git push origin ${{inputs.version}}